### ISSUE TITLE
Database schema revision

### ISSUE THREAD

**Issue by r-b-g-b** [openoakland/woeip#115]
**Is your feature request related to a problem? Please describe.**
Revisit the database schema to be straight forward for our current data needs (Dustrak/GPS) + able to accommodate future data needs. The current/first schema got us 90% of the way to what we need. I think this is a good time for a revision: we've had some time to notice some inadequacies of the current version, but we're not too far along that it will be a pain to make changes.

**Describe the solution you'd like**
Current data needs:
- One GPS file and one Dustrak file
- Organize raw data (so we can feel safe knowing that we can always get the raw data out if we need)
- Organize processed data (so we can quickly query measurements from a certain time/place)
- Know which raw data file each processed data point came from

Other data needs that are reasonable to imagine:
- A single raw data file that holds multiple data streams (perhaps multiple AQ measurements + GPS)

**Describe alternatives you've considered**
The current DB schema and the modification in #109 . I think these work great for our current data needs, but might become a bit convoluted for future data needs.

### For Developers
**Affected Components**
- Database schema: `models.py`
- Web upload: `forms.py', `views.py`

**Design Documentation**
https://www.lucidchart.com/invitations/accept/5adb4594-1f61-4230-936f-32b522302382

**Comment by r-b-g-b** [comment]
New design we hashed out tonight. I don't know anything about UML so apologies if this isn't quite right. Feel free to ask for changes. https://drive.google.com/file/d/1JYCJ1we1j8xr4gPGpIjTsiAE09J1mueI/view?usp=sharing

**Comment by ifed3** [comment]
@r-b-g-b, I can't access the document. can you share the ungated version?

**Comment by r-b-g-b** [comment]
Whoops, try the new link ^^^

**Comment by theecrit** [comment]
Looks great at first glance, @r-b-g-b. I'll take a closer look tomorrow. 

**Re: our naming conversation last night**
As a word nerd, I believe strongly that language is a critical component to making the database understandable to those who need to use it (current team and future teams, including potentially WOEIP staff). Here's a great approach that describes how to choose good names and how to format them to demonstrate meaningful relationships: https://openclassrooms.com/en/courses/4191736-design-a-database-with-uml/4191743-learn-about-class-diagrams

**Comment by TangoYankee** [comment]
1. The `Participant`/`User` labeling goes back to the conversation on how to manage the database of users. At the time, we decided that only members with accounts would be listed as uploaders/collectors. By extension, we would keep the standard `User` Django nomenclature.

2. I'm confused by trying track the relationship between `Calibration`, `Sensor`, and `Device`. I would prefer if they were one model. This also applies to `TimeGeo` and `Measurement`. I think it would be easier to understand if the fields for `TimeGeo` were moved directly into the `Measurement` model and `TimeGeo` eliminated.

3. I'm also confused when trying to find certain data traits in a separate meta-data model. I would prefer to eliminate this model.
    - The `joiner_version` could be made a field of the `Measurement` model
    - The relationships it tracks could be maintained by giving those models direct relationships with each other

From these notes, it seems that I'm mostly advocating to keep the database as-is. Also, as someone with an affinity for slimming down, my main change to the current database would be to eliminate the `Route` model, as we don't currently use it and can always add it back later.

I think a few style differences are appearing as well. I like fewer models with only fields I know I will need. I think @r-b-g-b prefers more models that include fields that may be needed in the future. Neither style is necessarily better. I just think it's good to acknowledge the different perspectives we bring :)

**Comment by ifed3** [comment]
Hey @TangoYankee, we spend most of Tuesday discussing some of the points you mentioned and broadly agreed to this schema definition. We aimed to solve both the specific use case of WOEIP but also create a schema that's flexible enough for a general use case.

I've attached a V2 of what @r-b-g-b created separated by the event domain. I'll explain some of the nuances

# Schema V2
![WOEIP Schema V2](https://user-images.githubusercontent.com/9001622/60361033-059d9880-9992-11e9-9a64-672d3bb00d17.jpg)

## Preparation Step

- A device in this schema functions as a collection of sensors, i.e. can have one or many sensors. 

In the WOEIP use case there's a simple 1-1 correspondence of device:sensor (dusttrak:photometer). But that need not always be the case. This schema reflects that.

- A sensor belongs to a device and a broad sensor category, what uniquely identifies a sensor is the measurement unit it outputs

- A sensor can be calibrated multiple times by a user

### Table Examples
- User

| id | username | email | password
| ------------- | ------------- | ------------- | ------------- |
| 1  | person | person@gmail.com | $2a$11$1TzpVhdmmYSajbz9.pNs8.O.146i |

- Device

| id | name | serial | firmware
| ------------- | ------------- | ------------- | ------------- |
| 1  | Dusttrak  | FA893202  | AF89ASFSDFDSA  |
| 2  | GPS Receiver | TK32LDJFS8 | FJLKAFJS98D928 |
| 3  | Lead Measurer | YA892AL3 | LBKJ32K41233AF |

- SensorType

| id | name | description |
| ------------- | ------------- | ------------- 
| 1  | Aerosol | Aerosol monitors, commonly referred to as dust monitors, particulate monitors, light scattering laser photometers, and nephlometers, are used to measure dust, smoke, mist, fume, condensates, and fog |
| 2  | GPS | Collects locations |
| 3 | Lead | Measures amount of lead in air |

- Sensor

| id | device_id | sensor_type_id | unit
| ------------- | ------------- | ------------- | ------------- |
| 1  | 1 | 1 | ppm |
| 2  | 2 | 2 | nmea |
| 3| 3 | 3 | mg/m<sup>3</sup> |

- Calibration

| id | user_id | sensor_id | created_at
| ------------- | ------------- | ------------- | ------------- |
| 1  | 1 | 1 | 2019-06-28 16:45:54.727995|

## Operation Step

- This step involves the output of a collection which is simply a series of files from the sensors, who collected them and where the files are now stored

- The processor version lives on the collection file since it's the file that's being processed not its results

- This format enables the storage of multiple collectors per collection file per collection

### Table Examples
- Collection

| id | starts_at | ends_at |
| ------------- | ------------- | ------------- |
| 1  |  2019-06-28 16:50:54.727995 |  2019-06-28 17:50:54.727995 |

- CollectionFile

| id | collection_id | sensor_id | user_id | url | uploaded_at | processor_version | processed_at  |
| ------------- | ------------- | ------------- | -------------  | ------------- | ------------- | ------------- | ------------- |
| 1  | 1 | 3 | 1 | s3.aws..../lead.csv |  2019-06-28 18:25:54.727995 | NULL | NULL |
| 2  | 1 | 1 | 1 | s3.aws..../dusttrak.csv |  2019-06-28 18:25:54.728452 | NULL | NULL |
| 3  | 1 | 2 | 1 | s3.aws..../gps.log |  2019-06-28 18:25:54.738986 | NULL | NULL |


## Processing Step
The files uploaded from the collection step are now resolved into timegeo series and analyte measurements. The reason for separation is twofold:

1. It supports storage of multiple pollutants at the same time and location if you introduce multiple devices or multiple sensors measuring different analytes
2. It allows a direct belongs_to linkage between processed data and the source file

- TimeGeo

| id | collection_file_id | location | time
| ------------- | ------------- | ------------- | ------------- |
| 1  |  3 | 37° 48' 15.7068'' N, 122° 16' 15.9996'' W | 2019-06-28 16:50:55 |
| 2  |  3 | 37° 49' 15.7070'' N, 122° 17' 15.9999'' W | 2019-06-28 16:50:56 |

- Analyte

| id | collection_file_id | time_geo_id | value
| ------------- | ------------- | ------------- | ------------- |
| 1  |  1 | 1 | 0.001 |
| 2  |  2 | 1| 0.2 |
| 3  |  1 | 2 | 0.002 |
| 3  |  2 | 2 | 0.3 |

Upon completion of processing, the collection file table is updated

- CollectionFile

| id | collection_id | sensor_id | user_id | url | uploaded_at | processor_version | processed_at  |
| ------------- | ------------- | ------------- | -------------  | ------------- | ------------- | ------------- | ------------- |
| 1  | 1 | 3 | 1 | s3.aws..../lead.csv |  2019-06-28 18:25:54.727995 | 1.1 | 2019-06-28 18:26:54.239033 |
| 2  | 1 | 1 | 1 | s3.aws..../dusttrak.csv |  2019-06-28 18:25:54.728452 | 1.1 | 2019-06-28 18:26:54.239033|
| 3  | 1 | 2 | 1 | s3.aws..../gps.log |  2019-06-28 18:25:54.738986 | 1.1 | 2019-06-28 18:26:54.239033 |

Happy to discuss this in person if you find it confusing!

**Comment by theecrit** [comment]
@TangoYankee Before we go too much further, let me clarify a couple of things that may help...

**Modeling principles**
The conclusion we came to as a group on Tues (we being @nbilenko, @ifed3, @Ethan-bradley, @r-b-g-b, Niels, and myself), was to prioritize normalization and one-to-one relationships for the sake of flexibility and potential ability to scale, while recognizing that our priority use case is still fairly limited. The result is a more tables, which allows to normalize the data more effectively. We decided that given the size of our data set at this stage, the resulting potential load trade-off (for both system and human developers!) was worth making in exchange for this flexibility/scalability. (@ifed3, @nbilenko: is this a fair description?)

**Goals/requirements**
As we pulled all this stuff apart on Tues, a number of different constraints and requirements kept popping up, which @ifed3 has captured above. Examples include:
- The need to maintain a record/relationship between which joiner script version (what Ife has named _processor_ above) was used on a given file pair (to enable data integrity checks if/when needed);
- The desire to accommodate future sensor types and measurement units (this is rapidly looming as a likely requirement in the not-too-distant future);
- Probably others.

**Asides/Addenda**
- I'd argue we need to add a "Role" attribute to the "User" table (since some users e.g. will have upload permissions but no deletion/edit permissions, while others will have both).

I think it's worth taking this week for everybody to digest these materials, ask questions, etc., then come back together in person next week to discuss and finalize. Trying to debate and explain these complexities online is inherently difficult, so let's use this forum to get the questions aired, and then make our decisions in-person together. Does that sound reasonable to y'all?

Lastly, I've found this explanation of database modeling to be extremely useful and digestible: https://launchschool.com/books/sql/read/table_relationships

We're tackling a lot (a complex problem space, mixed skill sets, a remote and unpaid team, etc), and I'm so impressed with what all of you have been bringing to the table. We're making really good progress here.

**Comment by r-b-g-b** [comment]
Whoa love the graph @ifed3 . Splitting up by domain is very nice, I'll keep that in mind in the future. Naming tweak: I'd call `SensorType` ->`Analyte` and `Analyte`->`Measurement`, but I won't die on that hill. Totally agree with @theecrit that this is best hashed out in person next week. Slight hitch: I'll be gone starting next week.

However, my design requirements can be summed up pretty simply:

1. Do we store the raw data files? (Yes for all schema so far)
2. Do we store all measurements in a way that is easily queryable in the form "Get me all measurements of analyte [A], near lat/long [B], on date [C]"? (Yes for all schema so far)
3. Can we easily find out which raw data file a measurement came from? Bonus for including some idea of how the raw data were processed to yield the measurement.
4. Can we do all of this when we have 2+ raw data files, each with one stream (as we have with Dustrak/GPS situation) AND when we have one raw file that contains multiple data streams (a single raw data file containing multiple analyte measurements + GPS). (No for current schema, yes for the proposed schema.)

If we keep the proposed schema I will be :) If we change the schema and can still answer yes to all of those requirements I will be :)

**Comment by TangoYankee** [comment]
Thank you @r-b-g-b @theecrit and @ifed3 for the documentation and explanation. I'm learning a lot from this discussion and the linked resources. I'll absorb and internalize as much as I can for Tuesday.

**Comment by theecrit** [comment]
I'd agree that `SensorType` and `Analyte` language could be a little clearer. Using plain, unambiguous language whenever possible is important for accessibility reasons. "Pollutant" is the commonly used term among our audience to describe what we're calling "SensorType," so that would be my recommendation.

I like "Measurement," or even "PollutantValue," to make it clearer.

**Comment by theecrit** [comment]
Here's the latest model from @ifed3:

![WOEIP Schema V2 (2)](https://user-images.githubusercontent.com/32755410/60558301-8bf10c00-9cfd-11e9-8116-136cafbefc9d.jpg)

**Comment by theecrit** [comment]
Closing this issue as resolved per the latest model above. I'll open a new issue for implementation of the new model.
