### ISSUE TITLE
As a developer, I want to include static files when developing locally

### ISSUE THREAD

**Issue by r-b-g-b** [openoakland/woeip#149]
Currently the standard development mode of `docker-compose up --build` does not serve the static files for the API UI.

**To replicate**

```
docker system prune --volumes
docker-compose up --build
```

And visit http://api.lvh.me No static files, very :(

**Describe the solution you'd like**
One fix is to add the static urls to the `woeip/api/woeip/urls.py` with the following:
```
from django.conf import settings
from django.conf.urls.static import static
from .settings import DEBUG

if DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
```

This (plus running `collectstatic` from the `woaq-api` container) works. However, there might be a better way to do it.

**Describe alternatives you've considered**
Our docker compose setup does have an nginx proxy that *I think* should handle serving the static files locally. It might be better to find out how to fix this than to force django to serve the files.

**Comment by r-b-g-b** [comment]
Don't have time to read these at the moment, but could have some useful bits:

- https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
- https://medium.com/faun/tech-edition-django-dockerization-with-bells-and-whistles-and-a-tad-bit-of-cleverness-2b5d1b57e289

**Comment by jayqi** [comment]
Read a bunch about this. I think ultimately the directions here are going to be most relevant because it's specifically about serving static files with jwilder/nginx-proxy: https://stackoverflow.com/questions/54571819/serving-static-files-from-jwilder-nginx-proxy

This article from the Django docs is also helpful just about the general topic of Django and static files: https://docs.djangoproject.com/en/2.2/howto/static-files/

I'm going to take a crack at getting this to work.

**Comment by jayqi** [comment]
I got it all to work! Need permissions to push my branch though. 

<img width="600" alt="Screen Shot 2019-11-14 at 10 04 58 PM" src="https://user-images.githubusercontent.com/2721979/68920696-e201a180-072a-11ea-9cd4-5a719d85357e.png">
