### ISSUE TITLE
Dustrak and GPS File names: Refactor Front End

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#221]
High-level comment - sometimes the files are distinguished using terms 'csv' and 'log' (like here) and sometimes 'gps' and 'dustrak' (elsewhere). It would be better to use the same naming scheme and make it fairly use case agnostic (e.g. 'gps'/'sensor' or 'location'/'sensor').

_Originally posted by @nbilenko in https://github.com/openoakland/woeip/pull/214_

Proposed Solution:
[Use GPS and Dustrak naming convention](https://github.com/openoakland/woeip/pull/214#discussion_r428183524)

**Comment by theecrit** [comment]
Language will necessarily vary based on context but yes, definitions and usage should be consistent. For example:

**Definitions:**
- _Device:_ The term for a physical unit used to collect data. 
  - Instantiation: Make + Model (e.g. DustTrak II 8530, AMOD AGL3080)
- _Sensor:_ The term for a physical _part_ of a device used to collect _a specific type_ of data. 
 - Instantiation: Varies; on single-sensor devices it might be a generic _PM 2.5 air quality sensor_, on multi-sensor devices it might be branded (e.g. _MQ-135 gas sensor_).
- _Make:_ The brand name of a device or sensor.
- _Model:_ The specific version produced by a device or sensor brand.
- _Unit:_ The nickname given to a specific device to differentiate it other devices of the same make/model.
- _File format:_ extension appended to the end of a file name (e.g. _csv_, _log_)

**Usage:**
- When referring to generic categories or groups of things that may contain multiple makes/models/units, use the generic terms.
- When referring to specific units or file formats, particularly where the specificity impacts accuracy or task success, use the more specific make/model/unit/file format reference.

**Examples:**
- Form field label for a drop-down should be labelled generically as _Device_.
- Options in a drop-down menu labelled "Device" should be specific make + model + unit<sup>1</sup> (e.g. DustTrak II 8530, unit B).
- When a user attempts to upload a Word doc instead of a csv file, specify the specific file format in the error displayed (e.g. "We need one csv and one log file").
- When greater clarity is needed to aid user understanding, include greater levels of info (e.g. in an introductory instruction, use something like "Let's upload a CSV from your DustTrak and a log file from your GPS device." Note in this example, we're saying _GPS device_ because it's a single-sensor device and the user is likely to think of it in these less specific terms<sup>2</sup>). 


<sup>1</sup> This should be up for debate, since it will be user-driven and we need to think about the technical and user flow implications of how the list gets populated.

<sup>2</sup> This may also be up for debate, depending on the outcome of the previous debate.

**Comment by theecrit** [comment]
If folks feel the above is practical, I'll document it more permanently somewhere.

**Comment by theecrit** [comment]
Will be addressed alongside other work.
