### ISSUE TITLE
As a developer, I would like retrieve a list of collections based on their start date

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#239]
**Is your feature request related to a problem? Please describe.**
Collections can currently only be retrieved by their ids. I would like to send a query string to retrieve a list of collections that occured on a given day.

**Describe the solution you'd like**
A url structured as `api.[domain]/collection?start_date=[yyyy-mm-dd]` should return a list of collections from that day.

**Additional context**
This query will be used in the map view in order to get collections by day. It will require a second request to get the data of a collection. ie) `api.[domain]/collection/{id}/data` Issue #133 

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
The collection view will need a query set.

**Technical Resources**
[DRF Filtering](https://www.django-rest-framework.org/api-guide/filtering/)

**Design Documentation**
Wireframes or other design resources

**Testing Outline**
Test within the view test suite.

**Comment by theecrit** [comment]
While I can't speak to the specific query process, I do have a couple of questions about how user interaction and use cases may impact the definition of this issue (though they likely have implications beyond this issue):

The database schema doesn't indicate the format for `timestamp` but I'd have assumed it would be `yyyy-mm-dd-hh-mm-ss` rather than simply `yyyy-mm-dd`. In which case, we'd probably want `api.[domain]/collection?start_date=[yyyy-mm-dd]` to be `api.[domain]/collection?start_date=[yyyy-mm-dd-hh-mm-ss]`. However, looking at the CSV data, it looks like the DustTrak only records date, start time, duration, and reading intervals. 

So my question is a two-fer: 
1. Does each data point in the database need a more specific `hh-mm-ss` stamp? I suspect we don't need it for MVP, but I could see potentially ingesting future data sets that do use the more specific `hh-mm-ss` addition.
2. If so, do we need to create a couple of issues to 1) update the database accordingly and 2) build a process to convert the DusTrak data into the more specific format?

Finally, another argument for incorporating the `hh-mm-ss` format is that as a user, I might want to query a 2-hour time period on a given day. This doesn't have to be in MVP but it will probably need to be implemented soon after.

**Comment by theecrit** [comment]
Oh yeah, and next question: do we need to include `end date and time` in the query, too? As a user, I may want a range of dates. Again, this can be post-MVP but I'd like to create an issue and make sure we're not building something now that we'll have to unbuild right after launch.

**Comment by TangoYankee** [comment]
1) Each data point already has its time recorded in the database. We're just not using time right now because the UI doesn't care.
2) a. Nope, it already holds that data b. Maybe? But that should be captured in issue #186
  
*Bonus Question!* The way queries work, we can send multiple parameters that build off each other. If we want a range, we can just add a second parameter later called `end_date`. It would only be minor change from what we we're building here.

**Comment by theecrit** [comment]
Copy that.

**Comment by Ajay-Vishwanath** [comment]
> Additional context
This query will be used in the map view in order to get collections by day. It will require a second request to get the data of a collection. ie) api.[domain]/collection/{id}/data Issue #133

Just to be clear the response for this request will be a list of collection IDs and then for the specific session mapping, an additional API request will need to be made to retrieve that collection's data, correct? Would there be a way to include that nested data in the initial response?

**Comment by TangoYankee** [comment]
> Would there be a way to include that nested data in the initial response?

I'd like to keep it as two separate operations, to maintain a separation of concerns.
