### ISSUE TITLE
Swagger docs not updating with code updates

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#241]
**Describe the bug**
The Swagger docs appear to be out of date. They should be updating when the codebase is updated but they don't appear to be doing so. This was noticed when @TangoYankee checked the Swagger docs for the call to access the `collection_id` via the `CollectionFile` but didn't find it. (Tim, please confirm if that's accurate and update accordingly.) 

**To Reproduce**
1. @TangoYankee can you update this when you have a chance?

**Expected behavior**
Swagger docs should automatically update to reflect the latest codebase when there are changes.

**Affected Components (For Developers)**
api.lvh.me/swagger

**Technical Resources (For Developers)**
Add links to appropriate documentation. Describe possible code implementations.

**Comment by jayqi** [comment]
I don't think this issue is accurate. The problem that @TangoYankee ran into is not that the Swagger docs are out of date or incorrect. The Swagger docs are correct representations of the API and are fine, and these are automatically generated by the application live. 

The problem that @TangoYankee ran into is that the API is distinct from the underlying database models and not a complete representation. @TangoYankee was looking for the relationship from `PollutantValue` to `CollectionFile`. This is a relationship that [exists in the database](https://github.com/openoakland/woeip/blob/2b8b833f801af24d91f9d1488b91696dd9ca6bb0/api/woeip/apps/air_quality/models.py#L133), but that relationship is [_not_ configured to be returned by the API](https://github.com/openoakland/woeip/blob/2b8b833f801af24d91f9d1488b91696dd9ca6bb0/api/woeip/apps/air_quality/serializers.py#L53-L59). In order to get this relationship to show up in Swagger, we would need to change the API to include that relationship. 

Swagger is a specification for documenting APIs, and not a specification for documenting database entities. We'd need new documentation if we want database documentation.

**Comment by TangoYankee** [comment]
@jayqi  Thank you for the clarification on the Swagger documentation.
