### ISSUE TITLE
Weird delete behavior following upload of multiple mismatched/duplicated files

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#268]
**Describe the bug**
With a pack of files uploaded, attempting certain files causes phantom behavior when attempting to clean up the batch.

**To Reproduce**
1. Go to lvh.me
2. Click on "Select files from your computer"
3. Select one csv and gps file whose dates don't match
4. Observe "dates don't match" warning
5. Click "Select files from your computer" without deleting anything
6. Select a group of csv and log files, including the originally uploaded pair
7. Observe "We need exactly one GPS log file and one DusTrak cvs file. Please remove additional files." warning
8. Delete one of the files. Nothing happens.
9. Delete a different files. File deletes.
10. Delete another file. Observe first deleted file be displayed again, without deleting the one I just clicked.
11. Continue clicking randomly wondering WTF is happening. 
12. Record screen.

**Expected behavior**
- Uploading a batch of files would cause only the non-dupes to upload beside the existing the files. 
- Deleting a file would delete the file.
- Deleting another file would delete that file and cause another to re-display.

**Screenshots**
[Screen grab](https://drive.google.com/file/d/1DMJGxoroMJwxws_LrN2Y53oWSaC1_P_0/view?usp=sharing)

**Desktop (please complete the following information):**
 - OS: OSX 10.15.7
 - Browser: Firefox 83.0, Chrome 87.0.4280.67

**Additional context**

I suspect this is directly related to the need for #176

**Comment by TangoYankee** [comment]
> Deleting a file would delete the file.
Deleting another file would delete that file and cause another to re-display.

I would consider these to be in the scope of the solving the immediate bug. I believe the bug comes from the way react uses keys to identify list items. Because we were using the file path as the key, uploading a duplicate file would make a duplicate key. This seems to be confusing React when it tries to delete a file. I'm sending up a fix now where I combine the `file.path` with the file's `index` in the file list. This will make the key unique and should clear up the confusion on delete.

>Uploading a batch of files would cause only the non-dupes to upload beside the existing the files.

This feels like it's out of scope for a bug and crosses into a feature request. Right now, we only support uploading one pair at a time.

**Comment by theecrit** [comment]
Closed by #269
