### ISSUE TITLE
Calendar in production build greys out all dates

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#443]
**Describe the bug**  
When viewing the production application, the map calendar shows grey boxes in place of all its dates.

**To Reproduce**  
1. Create a production build with `npm run build`
2. Serve the application with `serve build`
3. View the map calendar

**Expected behavior**  
All dates are viewable. Dates with sessions are clickable and have custom styling. Dates without sessions are disabled

**Screenshots**   
![Grey Calendar options](https://user-images.githubusercontent.com/11068062/161383419-46ce666e-e656-4446-bf09-93a525831a8e.PNG)

**Desktop (please complete the following information):**
 - Firefox and Chrom

**Affected Components (For Developers)**
Map -> Menu -> Calendar

**Comment by gsehrlich** [comment]
Fascinating, thanks. I did some questionable styling that worked in development but may have broken the production application. I'd love to take on this issue if I can get some help from someone building and serving the production code locally; my first attempt just now resulted in some nonsensical syntax errors. In the meantime I can start debugging using woaq.org.

**Comment by gsehrlich** [comment]
Looks like the graying-out problem happens because the production application parses custom styling differently somehow.

1. It's interpreting `opacity: 100%` on menu.css line 13 as `opacity: 1%`, hence the gray background showing through.
2. The ordering is different, so <style> is overriding menu.css instead of vice versa, hence the gray background in .clndr-days instead of white, and other differences.

I suspect this can be fixed for MVP by reverting some of the styling changes. Might not be as pretty though.
