### ISSUE TITLE
Organize technical instructions

### ISSUE THREAD

**Issue by r-b-g-b** [openoakland/woeip#62]
**Is your feature request related to a problem? Please describe.**
The technical instructions in the README/contributing docs is a bit disorganized.

**Describe the solution you'd like**
README should contain enough for a moderately-experienced developer to go from cloning the repo to running the site locally.

Less experienced developers might want more detailed instruction, (links to git, docker, django tutorials). I suggest this go in the ``Code Development`` section of ``contributing.md``. If even more detail is needed, we can make separate markdown documents, linked in ``contributing.md``. 

**Added from Issue 61**
The Getting Started section of the readme could be made more user-friendly by adding the following steps:
- After make local.up, run make local.shell. Add ./manage.py createsuperuser to add in a username/password.
- Go to localhost:8080 to access the site. Login with the username/password created above.

**Labels**
- [x] Add a status label
- [x] Add additional labels as needed

**Comment by Ethan-bradley** [comment]
@r-b-g-b See the issue #61 I added for further simplification ability.

**Comment by theecrit** [comment]
Added @Ethan-bradley's feedback from #61 (closed that issue as a duplicate), and changed label to "Discussing" since there appears to be multiple approaches under consideration.

**Comment by TangoYankee** [comment]
If we start adding detailed documents in the `.github` folder, it can start to feel cluttered. In the two other projects I've worked on, we instead provided a Beginner's Guide in the wiki. Here is an example one for [TrashTalk](https://github.com/openoakland/TrashTalk/wiki/New-Developer-Guide). We can add a line in the **Code Development**  section of the woeip contributing doc that says:
> For more detailed instructions on getting starting, follow the [Beginner's Guide](https://github.com/openoakland/woeip/wiki) in the wiki

**Comment by TangoYankee** [comment]
Proposed Structure:
- Move **Getting Started** from `readme.md` to `contributing.md`, under **Code Devopment**
- From @Ethan-bradley, add to **Getting Started**
  - > After make local.up, run make local.shell. Add ./manage.py createsuperuser to add in a username/password. Go to localhost:8080 to access the site. Login with the username/password created above.
- Move **Deployment** and **Terraform** information to the wiki
- Add more in-depth explanations of Docker, docker-compose, nginx, and other concepts to a **New Developer's Guide** in the wiki

**Comment by Ethan-bradley** [comment]
That sounds like a good structure plan to me.

**Comment by theecrit** [comment]
While I tend to lean towards @TangoYankee's approach because it avoids reinventing the wheel, it's also worth considering the following: we're trying to build a system that's sustainable for WOEIP over time. We're also trying to build a solution rooted in the community it's intended to serve. In the spirit of community-driven problem solving, it's worth asking ourselves *how might we...create documentation that's accessible to and usable by the community that the codebase is meant to serve?*

I don't have an answer to this question, but would love to hear folks' thoughts.

**Comment by Ethan-bradley** [comment]
Currently, the dustrak.py is not set up to edit the data after it pulls it from the files (needed for the form after uploading the data). Therefore, in order to edit the data in a form afterwards, the dustrak.py will need to be edited in order to fulfill that request. 

Overall, the functionality is a good idea as it would allow the users to edit the data if there is a mistake in there. However, many users may not know if there is an error in their data and this functionality would rarely be used. Therefore, it may be better to not include this in the MVP. 

However, some fields will still be needed such as the route. 

Additionally, currently I am using ajax to transfer the data from the javascript to the views.py.

**Comment by r-b-g-b** [comment]
I pushed a branch https://github.com/openoakland/woeip/tree/rg/technical-docs-%2362 that has everything except moving the Deployment and Terraform to the wiki. Is there general consensus about starting a project wiki and moving the Deployment and Terraform docs there? I'm in favor.

**Comment by TangoYankee** [comment]
I'm in favor of making a wiki. I vote to make the wiki and move the Deployment and Terraform sections to it. Then, this branch will be ready for a PR.
