### ISSUE TITLE
`make docker.build` fails

### ISSUE THREAD

**Issue by kiwisquash** [openoakland/woeip#77]
**Describe the bug**
Running `make docker.build` gives the following error:

`W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found`

**To Reproduce**
1. Go to the local copy of the git repository on terminal
2. Run `make docker.build`
3. See the error, be sad

**Screenshots**
<img width="570" alt="Screen Shot 2019-03-26 at 4 26 03 PM" src="https://user-images.githubusercontent.com/34022735/55048059-11309a80-5004-11e9-975c-4e2c34932094.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add a `bug` label
- [ ] Add additional labels as needed

**Comment by TangoYankee** [comment]
The cdn appears to have stopped carrying the image: [Debian Jessie CDN 404](http://cdn-fastly.deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages)

**Comment by TangoYankee** [comment]
I'm exploring other base images for python 3.6. 
The project originally used alpine. However, it was incompatible with the docker image for postgis.

**Comment by TangoYankee** [comment]
As a temporary patch, switch the docker base image from `python3.6-jessie` to `python3.6`. If the jessie cdn is still down tomorrow, we may need to integrate this new base image into the code base. Or, find a different base image.

**Comment by clintonb** [comment]
Here is an explanation of the issue: https://github.com/circleci/circleci-images/issues/366.

Jessie (Debian 8) is nearing EOL: https://wiki.debian.org/DebianReleases#Production_Releases, so repos were archived. The solution is to upgrade to a later version of Debian (e.g. Stretch). `python3.6` will always link to the latest version of Debian (e.g. `stretch` until 2020), so that is wise to use. Note, however, that there may be issues when the OS changes if you have code that is OS-dependent (which you most likely shouldn't).
